import type { SoundDesignSlotCategory } from '@storyteller/timeline'
import type { SoundAsset } from './sound-assets.js'

export const SOUND_LIBRARY: SoundAsset[] = [

  // ─── AMBIENT ────────────────────────────────────────────────────────────────

  {
    id: 'ambient-office-hvac-steady',
    name: 'Office HVAC Steady Hum',
    category: 'ambient',
    tags: ['office', 'HVAC', 'hum', 'indoor', 'quiet', 'steady'],
    worksWith: ['office', 'workplace', 'work', 'desk', 'meeting', 'building'],
    energy: 0.12,
    cinematic: 0.25,
    corporate: true,
    durationSeconds: 60,
    tailLengthSeconds: 1.5,
    recommendedForDna: ['netflix_documentary', 'bloomberg_finance', 'crime_documentary'],
    excludedFromDna: ['espn_sports'],
    provider: 'local',
    localPath: 'assets/ambient/office-hvac-steady.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'ambient-small-office-room-tone',
    name: 'Small Office Room Tone',
    category: 'ambient',
    tags: ['office', 'room tone', 'quiet', 'indoor', 'neutral'],
    worksWith: ['office', 'interview', 'conversation', 'meeting', 'small room'],
    energy: 0.08,
    cinematic: 0.2,
    corporate: true,
    durationSeconds: 60,
    tailLengthSeconds: 1.0,
    recommendedForDna: ['netflix_documentary', 'bloomberg_finance', 'podcast', 'crime_documentary'],
    excludedFromDna: ['espn_sports'],
    provider: 'local',
    localPath: 'assets/ambient/small-office-room-tone.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'ambient-open-plan-office-keyboards',
    name: 'Open-Plan Office with Distant Keyboards',
    category: 'ambient',
    tags: ['office', 'keyboards', 'open plan', 'typing', 'chatter', 'busy'],
    worksWith: ['office', 'work', 'busy', 'team', 'startup', 'productivity'],
    energy: 0.22,
    cinematic: 0.2,
    corporate: true,
    durationSeconds: 60,
    tailLengthSeconds: 1.5,
    recommendedForDna: ['bloomberg_finance', 'netflix_documentary', 'apple_keynote'],
    excludedFromDna: ['espn_sports', 'podcast'],
    provider: 'local',
    localPath: 'assets/ambient/open-plan-office-keyboards.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'ambient-coffee-shop-murmur-light',
    name: 'Coffee Shop Murmur (Light)',
    category: 'ambient',
    tags: ['coffee shop', 'cafe', 'murmur', 'chatter', 'light', 'social'],
    worksWith: ['coffee', 'cafe', 'casual', 'meeting', 'relaxed', 'conversation'],
    energy: 0.28,
    cinematic: 0.3,
    corporate: false,
    durationSeconds: 60,
    tailLengthSeconds: 2.0,
    recommendedForDna: ['youtube_creator', 'podcast', 'motivational'],
    excludedFromDna: ['bloomberg_finance', 'espn_sports'],
    provider: 'local',
    localPath: 'assets/ambient/coffee-shop-murmur-light.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'ambient-apartment-room-tone-refrigerator',
    name: 'Apartment Room Tone (Refrigerator Audible)',
    category: 'ambient',
    tags: ['apartment', 'room tone', 'refrigerator', 'hum', 'domestic', 'quiet'],
    worksWith: ['home', 'apartment', 'domestic', 'kitchen', 'personal', 'intimate'],
    energy: 0.1,
    cinematic: 0.45,
    corporate: false,
    durationSeconds: 60,
    tailLengthSeconds: 1.0,
    recommendedForDna: ['netflix_documentary', 'crime_documentary'],
    excludedFromDna: ['espn_sports', 'bloomberg_finance'],
    provider: 'local',
    localPath: 'assets/ambient/apartment-room-tone-refrigerator.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'ambient-city-street-moderate-traffic',
    name: 'City Street Ambience (Moderate Traffic)',
    category: 'ambient',
    tags: ['city', 'street', 'traffic', 'urban', 'outdoor', 'cars'],
    worksWith: ['city', 'urban', 'outside', 'street', 'commute', 'neighborhood'],
    energy: 0.38,
    cinematic: 0.35,
    corporate: false,
    durationSeconds: 60,
    tailLengthSeconds: 2.0,
    recommendedForDna: ['motivational', 'youtube_creator', 'crime_documentary', 'netflix_documentary'],
    excludedFromDna: ['bloomberg_finance'],
    provider: 'local',
    localPath: 'assets/ambient/city-street-moderate-traffic.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'ambient-outdoor-park-birds-wind',
    name: 'Outdoor Park — Birds and Light Wind',
    category: 'ambient',
    tags: ['park', 'birds', 'wind', 'outdoor', 'nature', 'peaceful'],
    worksWith: ['park', 'outside', 'nature', 'walk', 'morning', 'fresh air'],
    energy: 0.2,
    cinematic: 0.4,
    corporate: false,
    durationSeconds: 60,
    tailLengthSeconds: 2.5,
    recommendedForDna: ['netflix_documentary', 'motivational', 'youtube_creator'],
    excludedFromDna: ['bloomberg_finance', 'espn_sports'],
    provider: 'local',
    localPath: 'assets/ambient/outdoor-park-birds-wind.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'ambient-forest-dense-birdsong',
    name: 'Forest Dense Birdsong',
    category: 'ambient',
    tags: ['forest', 'birds', 'nature', 'dense', 'outdoor', 'wilderness'],
    worksWith: ['forest', 'woods', 'nature', 'wildlife', 'escape', 'wilderness'],
    energy: 0.25,
    cinematic: 0.5,
    corporate: false,
    durationSeconds: 60,
    tailLengthSeconds: 3.0,
    recommendedForDna: ['netflix_documentary', 'motivational'],
    excludedFromDna: ['bloomberg_finance', 'espn_sports', 'apple_keynote'],
    provider: 'local',
    localPath: 'assets/ambient/forest-dense-birdsong.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'ambient-car-interior-driving-steady',
    name: 'Car Interior Driving Steady',
    category: 'ambient',
    tags: ['car', 'driving', 'road', 'interior', 'engine', 'steady'],
    worksWith: ['car', 'drive', 'road trip', 'commute', 'travel', 'journey'],
    energy: 0.3,
    cinematic: 0.4,
    corporate: false,
    durationSeconds: 60,
    tailLengthSeconds: 2.0,
    recommendedForDna: ['netflix_documentary', 'crime_documentary', 'motivational'],
    excludedFromDna: ['espn_sports', 'bloomberg_finance'],
    provider: 'local',
    localPath: 'assets/ambient/car-interior-driving-steady.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'ambient-rain-window-light',
    name: 'Rain on Window (Light)',
    category: 'ambient',
    tags: ['rain', 'window', 'light rain', 'weather', 'indoor', 'patter'],
    worksWith: ['rain', 'weather', 'inside', 'reflective', 'quiet', 'contemplative'],
    energy: 0.18,
    cinematic: 0.55,
    corporate: false,
    durationSeconds: 60,
    tailLengthSeconds: 2.0,
    recommendedForDna: ['netflix_documentary', 'crime_documentary', 'motivational'],
    excludedFromDna: ['espn_sports', 'bloomberg_finance'],
    provider: 'local',
    localPath: 'assets/ambient/rain-window-light.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'ambient-rain-window-heavy',
    name: 'Rain on Window (Heavy)',
    category: 'ambient',
    tags: ['rain', 'window', 'heavy rain', 'storm', 'indoor', 'intense'],
    worksWith: ['storm', 'rain', 'heavy', 'dramatic', 'inside', 'shelter'],
    energy: 0.42,
    cinematic: 0.65,
    corporate: false,
    durationSeconds: 60,
    tailLengthSeconds: 2.5,
    recommendedForDna: ['crime_documentary', 'netflix_documentary'],
    excludedFromDna: ['espn_sports', 'bloomberg_finance', 'apple_keynote'],
    provider: 'local',
    localPath: 'assets/ambient/rain-window-heavy.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'ambient-late-night-apartment-silence',
    name: 'Late Night Apartment Silence',
    category: 'ambient',
    tags: ['late night', 'silence', 'apartment', 'quiet', 'still', 'dark'],
    worksWith: ['late night', 'insomnia', 'alone', 'quiet', 'dark', 'midnight'],
    energy: 0.05,
    cinematic: 0.6,
    corporate: false,
    durationSeconds: 60,
    tailLengthSeconds: 1.0,
    recommendedForDna: ['crime_documentary', 'netflix_documentary'],
    excludedFromDna: ['espn_sports', 'youtube_creator', 'bloomberg_finance'],
    provider: 'local',
    localPath: 'assets/ambient/late-night-apartment-silence.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  // ─── MOVEMENT ────────────────────────────────────────────────────────────────

  {
    id: 'movement-chair-creak-settle',
    name: 'Chair Creak and Settle',
    category: 'movement',
    tags: ['chair', 'creak', 'settle', 'foley', 'indoor', 'sit'],
    worksWith: ['sit', 'settle', 'interview', 'office', 'room', 'weight'],
    energy: 0.15,
    cinematic: 0.4,
    corporate: false,
    durationSeconds: 1.8,
    tailLengthSeconds: 0.3,
    recommendedForDna: ['netflix_documentary', 'crime_documentary'],
    excludedFromDna: ['espn_sports', 'bloomberg_finance'],
    provider: 'local',
    localPath: 'assets/movement/chair-creak-settle.mp3',
    format: 'mp3',
    channels: 1,
    sampleRate: 48000,
  },

  {
    id: 'movement-footsteps-hardwood',
    name: 'Footsteps on Hardwood',
    category: 'movement',
    tags: ['footsteps', 'hardwood', 'floor', 'walking', 'foley', 'indoor'],
    worksWith: ['walk', 'approach', 'enter', 'home', 'apartment', 'corridor'],
    energy: 0.25,
    cinematic: 0.35,
    corporate: false,
    durationSeconds: 4.0,
    tailLengthSeconds: 0.2,
    recommendedForDna: ['netflix_documentary', 'crime_documentary'],
    excludedFromDna: ['espn_sports', 'bloomberg_finance'],
    provider: 'local',
    localPath: 'assets/movement/footsteps-hardwood.mp3',
    format: 'mp3',
    channels: 1,
    sampleRate: 48000,
  },

  {
    id: 'movement-footsteps-concrete',
    name: 'Footsteps on Concrete',
    category: 'movement',
    tags: ['footsteps', 'concrete', 'pavement', 'walking', 'foley', 'outdoor'],
    worksWith: ['walk', 'street', 'urban', 'outside', 'alley', 'sidewalk'],
    energy: 0.28,
    cinematic: 0.4,
    corporate: false,
    durationSeconds: 4.0,
    tailLengthSeconds: 0.3,
    recommendedForDna: ['crime_documentary', 'motivational'],
    excludedFromDna: ['bloomberg_finance'],
    provider: 'local',
    localPath: 'assets/movement/footsteps-concrete.mp3',
    format: 'mp3',
    channels: 1,
    sampleRate: 48000,
  },

  {
    id: 'movement-paper-shuffle-page-turn',
    name: 'Paper Shuffle and Page Turn',
    category: 'movement',
    tags: ['paper', 'shuffle', 'page', 'turn', 'document', 'foley'],
    worksWith: ['paper', 'document', 'file', 'report', 'read', 'review'],
    energy: 0.1,
    cinematic: 0.2,
    corporate: true,
    durationSeconds: 1.2,
    tailLengthSeconds: 0.1,
    recommendedForDna: ['bloomberg_finance', 'netflix_documentary', 'podcast'],
    excludedFromDna: ['espn_sports'],
    provider: 'local',
    localPath: 'assets/movement/paper-shuffle-page-turn.mp3',
    format: 'mp3',
    channels: 1,
    sampleRate: 48000,
  },

  {
    id: 'movement-keyboard-typing-burst',
    name: 'Keyboard Typing Burst',
    category: 'movement',
    tags: ['keyboard', 'typing', 'keys', 'computer', 'burst', 'foley'],
    worksWith: ['type', 'write', 'email', 'code', 'work', 'computer', 'desk'],
    energy: 0.22,
    cinematic: 0.15,
    corporate: true,
    durationSeconds: 3.0,
    tailLengthSeconds: 0.1,
    recommendedForDna: ['bloomberg_finance', 'apple_keynote', 'youtube_creator'],
    excludedFromDna: ['espn_sports'],
    provider: 'local',
    localPath: 'assets/movement/keyboard-typing-burst.mp3',
    format: 'mp3',
    channels: 1,
    sampleRate: 48000,
  },

  {
    id: 'movement-coffee-mug-set-down',
    name: 'Coffee Mug Set Down on Table',
    category: 'movement',
    tags: ['coffee', 'mug', 'cup', 'table', 'set down', 'foley'],
    worksWith: ['coffee', 'tea', 'drink', 'table', 'pause', 'think'],
    energy: 0.12,
    cinematic: 0.3,
    corporate: false,
    durationSeconds: 0.8,
    tailLengthSeconds: 0.2,
    recommendedForDna: ['podcast', 'netflix_documentary', 'bloomberg_finance'],
    excludedFromDna: ['espn_sports'],
    provider: 'local',
    localPath: 'assets/movement/coffee-mug-set-down.mp3',
    format: 'mp3',
    channels: 1,
    sampleRate: 48000,
  },

  {
    id: 'movement-door-close-interior-soft',
    name: 'Door Close (Interior, Soft)',
    category: 'movement',
    tags: ['door', 'close', 'soft', 'interior', 'quiet', 'foley'],
    worksWith: ['door', 'close', 'leave', 'enter', 'room', 'privacy'],
    energy: 0.18,
    cinematic: 0.35,
    corporate: false,
    durationSeconds: 1.5,
    tailLengthSeconds: 0.4,
    recommendedForDna: ['netflix_documentary', 'crime_documentary'],
    excludedFromDna: ['espn_sports', 'bloomberg_finance'],
    provider: 'local',
    localPath: 'assets/movement/door-close-interior-soft.mp3',
    format: 'mp3',
    channels: 1,
    sampleRate: 48000,
  },

  {
    id: 'movement-jacket-clothing-rustle',
    name: 'Jacket and Clothing Rustle',
    category: 'movement',
    tags: ['jacket', 'clothing', 'rustle', 'fabric', 'foley', 'movement'],
    worksWith: ['jacket', 'clothes', 'put on', 'adjust', 'dress', 'coat'],
    energy: 0.1,
    cinematic: 0.25,
    corporate: false,
    durationSeconds: 1.5,
    tailLengthSeconds: 0.2,
    recommendedForDna: ['netflix_documentary', 'crime_documentary'],
    excludedFromDna: ['espn_sports', 'bloomberg_finance'],
    provider: 'local',
    localPath: 'assets/movement/jacket-clothing-rustle.mp3',
    format: 'mp3',
    channels: 1,
    sampleRate: 48000,
  },

  // ─── IMPACT ──────────────────────────────────────────────────────────────────

  {
    id: 'impact-low-cinematic-boom-restrained',
    name: 'Low Cinematic Boom (Restrained — Netflix Style)',
    category: 'impact',
    tags: ['boom', 'cinematic', 'low', 'restrained', 'bass', 'emotional'],
    worksWith: ['reveal', 'confession', 'realization', 'pivot', 'truth', 'moment'],
    energy: 0.35,
    cinematic: 0.85,
    corporate: false,
    durationSeconds: 2.5,
    tailLengthSeconds: 2.0,
    recommendedForDna: ['netflix_documentary', 'crime_documentary'],
    excludedFromDna: ['podcast', 'bloomberg_finance', 'apple_keynote'],
    provider: 'local',
    localPath: 'assets/impact/low-cinematic-boom-restrained.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'impact-mid-cinematic-boom',
    name: 'Mid Cinematic Boom (Moderate Energy)',
    category: 'impact',
    tags: ['boom', 'cinematic', 'mid', 'moderate', 'bass', 'accent'],
    worksWith: ['reveal', 'key moment', 'emphasis', 'turning point', 'decision'],
    energy: 0.6,
    cinematic: 0.8,
    corporate: false,
    durationSeconds: 2.0,
    tailLengthSeconds: 1.8,
    recommendedForDna: ['netflix_documentary', 'motivational', 'youtube_creator'],
    excludedFromDna: ['podcast', 'bloomberg_finance'],
    provider: 'local',
    localPath: 'assets/impact/mid-cinematic-boom.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'impact-heavy-cinematic-boom-espn',
    name: 'Heavy Cinematic Boom (ESPN Style)',
    category: 'impact',
    tags: ['boom', 'heavy', 'cinematic', 'ESPN', 'bass', 'impact', 'hard'],
    worksWith: ['touchdown', 'record', 'milestone', 'win', 'championship', 'achievement'],
    energy: 0.95,
    cinematic: 0.9,
    corporate: false,
    durationSeconds: 2.5,
    tailLengthSeconds: 2.5,
    recommendedForDna: ['espn_sports', 'motivational'],
    excludedFromDna: ['podcast', 'bloomberg_finance', 'apple_keynote'],
    provider: 'local',
    localPath: 'assets/impact/heavy-cinematic-boom-espn.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'impact-soft-bass-accent-corporate',
    name: 'Soft Bass Accent (Corporate)',
    category: 'impact',
    tags: ['bass', 'accent', 'soft', 'corporate', 'subtle', 'tone'],
    worksWith: ['data', 'reveal', 'earnings', 'statistic', 'announcement', 'metric'],
    energy: 0.2,
    cinematic: 0.35,
    corporate: true,
    durationSeconds: 1.2,
    tailLengthSeconds: 0.8,
    recommendedForDna: ['bloomberg_finance', 'apple_keynote'],
    excludedFromDna: ['espn_sports', 'podcast'],
    provider: 'local',
    localPath: 'assets/impact/soft-bass-accent-corporate.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'impact-sharp-metallic-hit-crime',
    name: 'Sharp Metallic Hit (Crime Doc)',
    category: 'impact',
    tags: ['metallic', 'sharp', 'hit', 'crime', 'sting', 'stab'],
    worksWith: ['name', 'reveal', 'crime', 'suspect', 'evidence', 'arrest', 'fact'],
    energy: 0.55,
    cinematic: 0.75,
    corporate: false,
    durationSeconds: 1.0,
    tailLengthSeconds: 1.2,
    recommendedForDna: ['crime_documentary', 'espn_sports'],
    excludedFromDna: ['podcast', 'bloomberg_finance'],
    provider: 'local',
    localPath: 'assets/impact/sharp-metallic-hit-crime.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'impact-warm-bass-pulse-motivational',
    name: 'Warm Bass Pulse (Motivational)',
    category: 'impact',
    tags: ['bass', 'warm', 'pulse', 'motivational', 'swell', 'forward'],
    worksWith: ['effort', 'training', 'push', 'action', 'start', 'begin', 'overcome'],
    energy: 0.65,
    cinematic: 0.7,
    corporate: false,
    durationSeconds: 2.0,
    tailLengthSeconds: 1.5,
    recommendedForDna: ['motivational', 'youtube_creator'],
    excludedFromDna: ['podcast', 'bloomberg_finance'],
    provider: 'local',
    localPath: 'assets/impact/warm-bass-pulse-motivational.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'impact-subtle-tension-hit',
    name: 'Subtle Tension Hit (Podcast-Safe)',
    category: 'impact',
    tags: ['tension', 'subtle', 'quiet', 'hit', 'accent', 'restrained'],
    worksWith: ['pause', 'weight', 'moment', 'silence', 'held breath', 'reveal'],
    energy: 0.15,
    cinematic: 0.55,
    corporate: false,
    durationSeconds: 1.5,
    tailLengthSeconds: 1.0,
    recommendedForDna: ['crime_documentary', 'netflix_documentary'],
    excludedFromDna: ['espn_sports', 'podcast'],
    provider: 'local',
    localPath: 'assets/impact/subtle-tension-hit.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'impact-deep-resonant-hit-trailer',
    name: 'Deep Resonant Hit (Trailer-Weight)',
    category: 'impact',
    tags: ['deep', 'resonant', 'hit', 'trailer', 'bass', 'weight', 'heavy'],
    worksWith: ['climax', 'reveal', 'finale', 'peak', 'culmination', 'conclusion'],
    energy: 0.88,
    cinematic: 0.95,
    corporate: false,
    durationSeconds: 3.0,
    tailLengthSeconds: 3.0,
    recommendedForDna: ['espn_sports', 'netflix_documentary', 'crime_documentary'],
    excludedFromDna: ['podcast', 'bloomberg_finance', 'apple_keynote'],
    provider: 'local',
    localPath: 'assets/impact/deep-resonant-hit-trailer.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  // ─── TRANSITION ──────────────────────────────────────────────────────────────

  {
    id: 'transition-gentle-whoosh-horizontal',
    name: 'Gentle Whoosh (Horizontal)',
    category: 'transition',
    tags: ['whoosh', 'gentle', 'horizontal', 'swipe', 'smooth', 'light'],
    worksWith: ['cut', 'transition', 'next', 'move', 'segment', 'chapter'],
    energy: 0.3,
    cinematic: 0.45,
    corporate: false,
    durationSeconds: 0.8,
    tailLengthSeconds: 0.3,
    recommendedForDna: ['youtube_creator', 'apple_keynote', 'motivational'],
    excludedFromDna: ['podcast', 'crime_documentary'],
    provider: 'local',
    localPath: 'assets/transition/gentle-whoosh-horizontal.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'transition-subtle-upward-swoosh-corporate',
    name: 'Subtle Upward Swoosh (Corporate)',
    category: 'transition',
    tags: ['swoosh', 'upward', 'subtle', 'corporate', 'clean', 'professional'],
    worksWith: ['transition', 'section', 'next topic', 'data', 'chart', 'slide'],
    energy: 0.18,
    cinematic: 0.3,
    corporate: true,
    durationSeconds: 0.6,
    tailLengthSeconds: 0.2,
    recommendedForDna: ['bloomberg_finance', 'apple_keynote'],
    excludedFromDna: ['espn_sports', 'podcast'],
    provider: 'local',
    localPath: 'assets/transition/subtle-upward-swoosh-corporate.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'transition-quick-downward-sweep',
    name: 'Quick Downward Sweep',
    category: 'transition',
    tags: ['sweep', 'downward', 'quick', 'whoosh', 'descent', 'fast'],
    worksWith: ['cut', 'drop', 'reveal', 'transition', 'fast cut', 'jump'],
    energy: 0.5,
    cinematic: 0.55,
    corporate: false,
    durationSeconds: 0.5,
    tailLengthSeconds: 0.2,
    recommendedForDna: ['youtube_creator', 'espn_sports'],
    excludedFromDna: ['podcast', 'bloomberg_finance'],
    provider: 'local',
    localPath: 'assets/transition/quick-downward-sweep.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'transition-tension-drone-bleed',
    name: 'Tension Drone Bleed',
    category: 'transition',
    tags: ['drone', 'tension', 'bleed', 'sustained', 'unresolved', 'dark'],
    worksWith: ['cut', 'transition', 'unresolved', 'tension', 'suspense', 'segment'],
    energy: 0.4,
    cinematic: 0.8,
    corporate: false,
    durationSeconds: 4.0,
    tailLengthSeconds: 3.0,
    recommendedForDna: ['crime_documentary', 'netflix_documentary'],
    excludedFromDna: ['espn_sports', 'podcast', 'youtube_creator'],
    provider: 'local',
    localPath: 'assets/transition/tension-drone-bleed.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'transition-crowd-energy-swell-sports',
    name: 'Crowd Energy Swell (Sports)',
    category: 'transition',
    tags: ['crowd', 'swell', 'sports', 'energy', 'stadium', 'roar'],
    worksWith: ['crowd', 'stadium', 'sports', 'game', 'arena', 'fans', 'energy'],
    energy: 0.88,
    cinematic: 0.7,
    corporate: false,
    durationSeconds: 3.0,
    tailLengthSeconds: 2.0,
    recommendedForDna: ['espn_sports'],
    excludedFromDna: ['podcast', 'bloomberg_finance', 'netflix_documentary'],
    provider: 'local',
    localPath: 'assets/transition/crowd-energy-swell-sports.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'transition-orchestral-riser-short',
    name: 'Orchestral Riser (Short)',
    category: 'transition',
    tags: ['orchestral', 'riser', 'swell', 'strings', 'build', 'cinematic'],
    worksWith: ['build', 'climax', 'swell', 'approach', 'anticipation', 'triumph'],
    energy: 0.72,
    cinematic: 0.85,
    corporate: false,
    durationSeconds: 2.5,
    tailLengthSeconds: 1.5,
    recommendedForDna: ['motivational', 'espn_sports'],
    excludedFromDna: ['podcast', 'bloomberg_finance'],
    provider: 'local',
    localPath: 'assets/transition/orchestral-riser-short.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'transition-silence-gap-breath',
    name: 'Silence Gap (Intentional Breath)',
    category: 'transition',
    tags: ['silence', 'gap', 'breath', 'pause', 'intentional', 'beat'],
    worksWith: ['pause', 'breath', 'beat', 'moment', 'transition', 'cut'],
    energy: 0.02,
    cinematic: 0.6,
    corporate: false,
    durationSeconds: 1.5,
    tailLengthSeconds: 0.0,
    recommendedForDna: ['netflix_documentary', 'podcast', 'crime_documentary'],
    excludedFromDna: ['espn_sports', 'youtube_creator'],
    provider: 'local',
    localPath: 'assets/transition/silence-gap-breath.mp3',
    format: 'mp3',
    channels: 2,
    sampleRate: 48000,
  },

  {
    id: 'transition-page-turn-swipe',
    name: 'Page Turn Swipe',
    category: 'transition',
    tags: ['page', 'turn', 'swipe', 'paper', 'book', 'transition'],
    worksWith: ['chapter', 'section', 'next', 'page', 'list', 'item', 'reveal'],
    energy: 0.22,
    cinematic: 0.3,
    corporate: false,
    durationSeconds: 0.6,
    tailLengthSeconds: 0.1,
    recommendedForDna: ['youtube_creator', 'apple_keynote'],
    excludedFromDna: ['podcast', 'crime_documentary'],
    provider: 'local',
    localPath: 'assets/transition/page-turn-swipe.mp3',
    format: 'mp3',
    channels: 1,
    sampleRate: 48000,
  },

  // ─── SILENCE ─────────────────────────────────────────────────────────────────

  {
    id: 'silence-ambient-duck-marker',
    name: 'Intentional Silence Marker (Ambient Duck)',
    category: 'silence',
    tags: ['silence', 'marker', 'ambient duck', 'intentional', 'hold', 'absence'],
    worksWith: ['reveal', 'silence', 'hold', 'pause', 'before', 'anticipation'],
    energy: 0.0,
    cinematic: 0.7,
    corporate: false,
    durationSeconds: 2.0,
    tailLengthSeconds: 0.0,
    recommendedForDna: ['netflix_documentary', 'crime_documentary', 'apple_keynote'],
    excludedFromDna: ['espn_sports', 'youtube_creator'],
    provider: 'local',
    localPath: 'assets/silence/ambient-duck-marker.mp3',
    format: 'mp3',
    channels: 1,
    sampleRate: 48000,
  },

  {
    id: 'silence-pre-reveal-hold',
    name: 'Pre-Reveal Silence Hold',
    category: 'silence',
    tags: ['silence', 'pre-reveal', 'hold', 'anticipation', 'breath', 'still'],
    worksWith: ['before', 'reveal', 'name', 'answer', 'fact', 'truth', 'announcement'],
    energy: 0.0,
    cinematic: 0.75,
    corporate: false,
    durationSeconds: 3.0,
    tailLengthSeconds: 0.0,
    recommendedForDna: ['netflix_documentary', 'crime_documentary'],
    excludedFromDna: ['espn_sports', 'youtube_creator'],
    provider: 'local',
    localPath: 'assets/silence/pre-reveal-hold.mp3',
    format: 'mp3',
    channels: 1,
    sampleRate: 48000,
  },

  {
    id: 'silence-post-confession-pause',
    name: 'Post-Confession Pause',
    category: 'silence',
    tags: ['silence', 'post-confession', 'pause', 'aftermath', 'weight', 'absorb'],
    worksWith: ['after', 'confession', 'admission', 'truth', 'reveal', 'emotion'],
    energy: 0.0,
    cinematic: 0.8,
    corporate: false,
    durationSeconds: 4.0,
    tailLengthSeconds: 0.0,
    recommendedForDna: ['netflix_documentary', 'crime_documentary', 'podcast'],
    excludedFromDna: ['espn_sports', 'youtube_creator', 'bloomberg_finance'],
    provider: 'local',
    localPath: 'assets/silence/post-confession-pause.mp3',
    format: 'mp3',
    channels: 1,
    sampleRate: 48000,
  },
]

export function getSoundLibrary(): SoundAsset[] {
  return SOUND_LIBRARY
}

export function getAssetById(id: string): SoundAsset | undefined {
  return SOUND_LIBRARY.find(a => a.id === id)
}

export function getAssetsByCategory(category: SoundDesignSlotCategory): SoundAsset[] {
  return SOUND_LIBRARY.filter(a => a.category === category)
}
